// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WasteFood.Data;

namespace WasteFood.Migrations
{
    // Fix: Implement the required abstract methods 'Up' and 'Down' from the 'Migration' base class.
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250703095036_clone admin")]
    internal class cloneadminBase : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Add migration logic here, e.g., creating tables, adding columns, etc.
            // Example:
            // migrationBuilder.CreateTable(
            //     name: "ExampleTable",
            //     columns: table => new
            //     {
            //         Id = table.Column<int>(nullable: false)
            //             .Annotation("SqlServer:Identity", "1, 1"),
            //         Name = table.Column<string>(nullable: true)
            //     },
            //     constraints: table =>
            //     {
            //         table.PrimaryKey("PK_ExampleTable", x => x.Id);
            //     });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Add rollback logic here, e.g., dropping tables, removing columns, etc.
            // Example:
            // migrationBuilder.DropTable(
            //     name: "ExampleTable");
        }
    }
}